spring.datasource.url=jdbc:postgresql://localhost:5432/drone_delivery
spring.datasource.username=drone
spring.datasource.password=drone

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
